// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {update} from '../models';
import {session} from '../models';
import {main} from '../models';
import {store} from '../models';
import {sync} from '../models';

export function AddColumn(arg1:string,arg2:string,arg3:string,arg4:database.ColumnDef):Promise<void>;

export function AddIndex(arg1:string,arg2:string,arg3:string,arg4:database.IndexDef):Promise<void>;

export function AppendFileBase64(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CancelChatStream():Promise<void>;

export function ChatCompletion(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<string>;

export function CheckForUpdate(arg1:string):Promise<update.UpdateInfo>;

export function ClearBackgroundImage():Promise<void>;

export function CloseSession(arg1:string):Promise<void>;

export function ConnectSerial(arg1:string,arg2:number,arg3:number,arg4:number,arg5:string):Promise<session.SessionInfo>;

export function CreateDatabase(arg1:string,arg2:string):Promise<void>;

export function CreateSession(arg1:string,arg2:session.ConnectionConfig):Promise<session.SessionInfo>;

export function CreateTable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DBDefaultTableQuery(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DBDeleteRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function DBInsertRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function DBUpdateRow(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>,arg5:Record<string, any>):Promise<void>;

export function DeleteTerminalHistoryEntry(arg1:Array<string>):Promise<void>;

export function DisableSessionOutputLog(arg1:string):Promise<void>;

export function DropColumn(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DropDatabase(arg1:string,arg2:string):Promise<void>;

export function DropIndexOp(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:Array<string>):Promise<void>;

export function DropTable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DropView(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EnableSessionOutputLog(arg1:string,arg2:string):Promise<string>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:string):Promise<database.QueryResult>;

export function ExecuteStatement(arg1:string,arg2:string,arg3:string):Promise<database.ExecResult>;

export function FetchModels(arg1:string,arg2:string):Promise<Array<main.ModelInfo>>;

export function FileSize(arg1:string):Promise<number>;

export function FrontendLog(arg1:string,arg2:string):Promise<void>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetAvailableShells():Promise<Array<string>>;

export function GetBackgroundImage(arg1:string):Promise<string>;

export function GetDBCapabilities(arg1:string):Promise<database.DBCapabilities>;

export function GetDatabases(arg1:string):Promise<Array<string>>;

export function GetDefaultSessionLogDir():Promise<string>;

export function GetDefaultShell():Promise<string>;

export function GetDesktopPath():Promise<string>;

export function GetDisks(arg1:string):Promise<Array<session.DiskInfo>>;

export function GetNetworkCards(arg1:string):Promise<Array<session.NetCardInfo>>;

export function GetPlatform():Promise<string>;

export function GetPorts(arg1:string):Promise<Array<session.PortInfo>>;

export function GetProcessDetail(arg1:string,arg2:number):Promise<Record<string, any>>;

export function GetRecentConnections():Promise<Array<string>>;

export function GetSessionOutputLogInfo(arg1:string):Promise<main.SessionLogInfo>;

export function GetSystemFonts():Promise<Array<string>>;

export function GetTableSchema(arg1:string,arg2:string,arg3:string):Promise<database.SchemaResult>;

export function GetTables(arg1:string,arg2:string):Promise<Array<database.TableInfo>>;

export function KillProcess(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ListSerialPorts():Promise<Array<string>>;

export function ListSessions():Promise<Array<session.SessionInfo>>;

export function ListTunnelStates():Promise<Array<session.TunnelState>>;

export function LoadAIConfig():Promise<store.AIConfig>;

export function LoadAISessions():Promise<store.AISessionData>;

export function LoadConnections():Promise<session.ConnectionStoreData>;

export function LoadLocalState():Promise<store.LocalState>;

export function LoadQuickCommands():Promise<store.QuickCommandData>;

export function LoadSettings():Promise<store.AppSettings>;

export function LoadTerminalHistory():Promise<Array<store.HistoryEntry>>;

export function LoadTunnels():Promise<session.TunnelStoreData>;

export function ModifyColumn(arg1:string,arg2:string,arg3:string,arg4:database.ColumnDef):Promise<void>;

export function MongoCreateCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MongoCreateIndex(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<void>;

export function MongoDeleteOne(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MongoDropCollection(arg1:string,arg2:string,arg3:string):Promise<void>;

export function MongoDropDatabase(arg1:string,arg2:string):Promise<void>;

export function MongoDropIndex(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function MongoFind(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number):Promise<session.MongoQueryResult>;

export function MongoGetDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function MongoInsertOne(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function MongoListCollections(arg1:string,arg2:string):Promise<Array<string>>;

export function MongoListDatabases(arg1:string):Promise<Array<string>>;

export function MongoListIndexes(arg1:string,arg2:string,arg3:string):Promise<Array<session.MongoIndexInfo>>;

export function MongoPing(arg1:string):Promise<void>;

export function MongoUpdateOne(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function OnConnectionsChanged(arg1:any):Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenFileDialogFiltered(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenMultipleFilesDialog():Promise<Array<string>>;

export function OpenPathInExplorer(arg1:string):Promise<void>;

export function RDPHide(arg1:string):Promise<void>;

export function RDPSetFocus(arg1:string,arg2:boolean):Promise<void>;

export function RDPSetPosition(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<void>;

export function RDPShow(arg1:string):Promise<void>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadFileChunkBase64(arg1:string,arg2:number,arg3:number):Promise<string>;

export function RecordRecentConnection(arg1:string):Promise<void>;

export function RedisDBSize(arg1:string):Promise<number>;

export function RedisDeleteKey(arg1:string,arg2:string):Promise<void>;

export function RedisGetHashAll(arg1:string,arg2:string):Promise<Array<session.FieldEntry>>;

export function RedisGetKeyInfo(arg1:string,arg2:string):Promise<session.RedisKeyInfo>;

export function RedisGetKeyTTL(arg1:string,arg2:string):Promise<number>;

export function RedisGetListRange(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<string>>;

export function RedisGetSetAll(arg1:string,arg2:string):Promise<Array<string>>;

export function RedisGetSortedSetRange(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<session.ScoredMember>>;

export function RedisGetString(arg1:string,arg2:string):Promise<string>;

export function RedisHashDel(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function RedisHashSet(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function RedisKeyExists(arg1:string,arg2:string):Promise<boolean>;

export function RedisKeyspaceInfo(arg1:string):Promise<Record<number, number>>;

export function RedisListPop(arg1:string,arg2:string,arg3:string):Promise<string>;

export function RedisListPush(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<number>;

export function RedisListRemove(arg1:string,arg2:string,arg3:string,arg4:number):Promise<number>;

export function RedisListSet(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function RedisPing(arg1:string):Promise<void>;

export function RedisScanKeys(arg1:string,arg2:string,arg3:number,arg4:number):Promise<session.ScanResult>;

export function RedisSetAdd(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function RedisSetKeyTTL(arg1:string,arg2:string,arg3:number):Promise<void>;

export function RedisSetRemove(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function RedisSetString(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RedisSwitchDB(arg1:string,arg2:number):Promise<void>;

export function RedisZSetAdd(arg1:string,arg2:string,arg3:Array<session.ScoredMember>):Promise<number>;

export function RedisZSetRemove(arg1:string,arg2:string,arg3:Array<string>):Promise<number>;

export function RegisterSessionForPanel(arg1:string,arg2:string):Promise<void>;

export function RemoveTempFile(arg1:string):Promise<void>;

export function SaveAIConfig(arg1:store.AIConfig):Promise<void>;

export function SaveAISessions(arg1:store.AISessionData):Promise<void>;

export function SaveConnections(arg1:session.ConnectionStoreData):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveFileDialogFiltered(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveLocalState(arg1:store.LocalState):Promise<void>;

export function SaveQuickCommands(arg1:store.QuickCommandData):Promise<void>;

export function SaveSettings(arg1:store.AppSettings):Promise<void>;

export function SaveTerminalHistory(arg1:Array<store.HistoryEntry>):Promise<void>;

export function SaveTunnels(arg1:session.TunnelStoreData):Promise<void>;

export function SaveWindowState(arg1:number,arg2:number,arg3:number,arg4:number,arg5:boolean):Promise<void>;

export function SessionEndZmodem(arg1:string):Promise<void>;

export function SessionResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SessionStartZmodem(arg1:string):Promise<void>;

export function SessionWrite(arg1:string,arg2:string):Promise<void>;

export function SessionWriteBinary(arg1:string,arg2:string):Promise<void>;

export function SetBackgroundImage(arg1:string):Promise<string>;

export function SetDefaultSessionLogDir(arg1:string):Promise<void>;

export function SetMonitorActiveTab(arg1:string,arg2:string):Promise<void>;

export function SetMonitorPaused(arg1:string,arg2:boolean):Promise<void>;

export function SftpCancelTransfer(arg1:string,arg2:string):Promise<void>;

export function SftpChangeLocalDir(arg1:string,arg2:string):Promise<session.FileListResult>;

export function SftpChangeRemoteDir(arg1:string,arg2:string):Promise<session.FileListResult>;

export function SftpChmod(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpCopy(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpGet(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function SftpGetContent(arg1:string,arg2:string):Promise<string>;

export function SftpListLocal(arg1:string,arg2:string):Promise<session.FileListResult>;

export function SftpListLocalDrives(arg1:string):Promise<Array<session.FileItem>>;

export function SftpListRemote(arg1:string,arg2:string):Promise<session.FileListResult>;

export function SftpLocalCopy(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpLocalGetContent(arg1:string,arg2:string):Promise<string>;

export function SftpLocalMkdir(arg1:string,arg2:string):Promise<void>;

export function SftpLocalMove(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpLocalPutContent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SftpLocalRemove(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SftpLocalRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpMakeDir(arg1:string,arg2:string):Promise<void>;

export function SftpMove(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpPauseTransfer(arg1:string,arg2:string):Promise<void>;

export function SftpPut(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function SftpPutContent(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SftpRemove(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SftpRename(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SftpResumeTransfer(arg1:string,arg2:string):Promise<void>;

export function StartTunnel(arg1:string):Promise<session.TunnelState>;

export function StopTunnel(arg1:string):Promise<void>;

export function SyncChangePassword(arg1:string,arg2:string):Promise<void>;

export function SyncConfigureRepo(arg1:string,arg2:string,arg3:string,arg4:string):Promise<sync.SyncResult>;

export function SyncDeleteRepo():Promise<void>;

export function SyncGetConfig():Promise<sync.SyncConfig>;

export function SyncNow():Promise<sync.SyncResult>;

export function SyncResolveConflict(arg1:boolean):Promise<sync.SyncResult>;

export function SyncSaveConfig(arg1:sync.SyncConfig,arg2:string):Promise<void>;

export function SyncTestConnection():Promise<void>;

export function SyncVerifyPassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function TruncateTable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnregisterSession(arg1:string):Promise<void>;

export function WriteFileBase64(arg1:string,arg2:string):Promise<void>;

export function WriteTempFile(arg1:string,arg2:string):Promise<string>;
