// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddColumn'](arg1, arg2, arg3, arg4);
}

export function AddIndex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddIndex'](arg1, arg2, arg3, arg4);
}

export function AppendFileBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['AppendFileBase64'](arg1, arg2, arg3);
}

export function CancelChatStream() {
  return window['go']['main']['App']['CancelChatStream']();
}

export function ChatCompletion(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['ChatCompletion'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function ClearBackgroundImage() {
  return window['go']['main']['App']['ClearBackgroundImage']();
}

export function CloseSession(arg1) {
  return window['go']['main']['App']['CloseSession'](arg1);
}

export function ConnectSerial(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConnectSerial'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateDatabase(arg1, arg2) {
  return window['go']['main']['App']['CreateDatabase'](arg1, arg2);
}

export function CreateSession(arg1, arg2) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2);
}

export function CreateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateTable'](arg1, arg2, arg3);
}

export function DBDefaultTableQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['DBDefaultTableQuery'](arg1, arg2, arg3);
}

export function DBDeleteRow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DBDeleteRow'](arg1, arg2, arg3, arg4);
}

export function DBInsertRow(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DBInsertRow'](arg1, arg2, arg3, arg4);
}

export function DBUpdateRow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DBUpdateRow'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteTerminalHistoryEntry(arg1) {
  return window['go']['main']['App']['DeleteTerminalHistoryEntry'](arg1);
}

export function DisableSessionOutputLog(arg1) {
  return window['go']['main']['App']['DisableSessionOutputLog'](arg1);
}

export function DropColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DropColumn'](arg1, arg2, arg3, arg4);
}

export function DropDatabase(arg1, arg2) {
  return window['go']['main']['App']['DropDatabase'](arg1, arg2);
}

export function DropIndexOp(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['DropIndexOp'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DropTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['DropTable'](arg1, arg2, arg3);
}

export function DropView(arg1, arg2, arg3) {
  return window['go']['main']['App']['DropView'](arg1, arg2, arg3);
}

export function EnableSessionOutputLog(arg1, arg2) {
  return window['go']['main']['App']['EnableSessionOutputLog'](arg1, arg2);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function ExecuteStatement(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteStatement'](arg1, arg2, arg3);
}

export function FetchModels(arg1, arg2) {
  return window['go']['main']['App']['FetchModels'](arg1, arg2);
}

export function FileSize(arg1) {
  return window['go']['main']['App']['FileSize'](arg1);
}

export function FrontendLog(arg1, arg2) {
  return window['go']['main']['App']['FrontendLog'](arg1, arg2);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetAvailableShells() {
  return window['go']['main']['App']['GetAvailableShells']();
}

export function GetBackgroundImage(arg1) {
  return window['go']['main']['App']['GetBackgroundImage'](arg1);
}

export function GetDBCapabilities(arg1) {
  return window['go']['main']['App']['GetDBCapabilities'](arg1);
}

export function GetDatabases(arg1) {
  return window['go']['main']['App']['GetDatabases'](arg1);
}

export function GetDefaultSessionLogDir() {
  return window['go']['main']['App']['GetDefaultSessionLogDir']();
}

export function GetDefaultShell() {
  return window['go']['main']['App']['GetDefaultShell']();
}

export function GetDesktopPath() {
  return window['go']['main']['App']['GetDesktopPath']();
}

export function GetDisks(arg1) {
  return window['go']['main']['App']['GetDisks'](arg1);
}

export function GetNetworkCards(arg1) {
  return window['go']['main']['App']['GetNetworkCards'](arg1);
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function GetPorts(arg1) {
  return window['go']['main']['App']['GetPorts'](arg1);
}

export function GetProcessDetail(arg1, arg2) {
  return window['go']['main']['App']['GetProcessDetail'](arg1, arg2);
}

export function GetRecentConnections() {
  return window['go']['main']['App']['GetRecentConnections']();
}

export function GetSessionOutputLogInfo(arg1) {
  return window['go']['main']['App']['GetSessionOutputLogInfo'](arg1);
}

export function GetSystemFonts() {
  return window['go']['main']['App']['GetSystemFonts']();
}

export function GetTableSchema(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2, arg3);
}

export function GetTables(arg1, arg2) {
  return window['go']['main']['App']['GetTables'](arg1, arg2);
}

export function KillProcess(arg1, arg2, arg3) {
  return window['go']['main']['App']['KillProcess'](arg1, arg2, arg3);
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListTunnelStates() {
  return window['go']['main']['App']['ListTunnelStates']();
}

export function LoadAIConfig() {
  return window['go']['main']['App']['LoadAIConfig']();
}

export function LoadAISessions() {
  return window['go']['main']['App']['LoadAISessions']();
}

export function LoadConnections() {
  return window['go']['main']['App']['LoadConnections']();
}

export function LoadLocalState() {
  return window['go']['main']['App']['LoadLocalState']();
}

export function LoadQuickCommands() {
  return window['go']['main']['App']['LoadQuickCommands']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadTerminalHistory() {
  return window['go']['main']['App']['LoadTerminalHistory']();
}

export function LoadTunnels() {
  return window['go']['main']['App']['LoadTunnels']();
}

export function ModifyColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ModifyColumn'](arg1, arg2, arg3, arg4);
}

export function MongoCreateCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['MongoCreateCollection'](arg1, arg2, arg3);
}

export function MongoCreateIndex(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['MongoCreateIndex'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function MongoDeleteOne(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MongoDeleteOne'](arg1, arg2, arg3, arg4);
}

export function MongoDropCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['MongoDropCollection'](arg1, arg2, arg3);
}

export function MongoDropDatabase(arg1, arg2) {
  return window['go']['main']['App']['MongoDropDatabase'](arg1, arg2);
}

export function MongoDropIndex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MongoDropIndex'](arg1, arg2, arg3, arg4);
}

export function MongoFind(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['MongoFind'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function MongoGetDocument(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MongoGetDocument'](arg1, arg2, arg3, arg4);
}

export function MongoInsertOne(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MongoInsertOne'](arg1, arg2, arg3, arg4);
}

export function MongoListCollections(arg1, arg2) {
  return window['go']['main']['App']['MongoListCollections'](arg1, arg2);
}

export function MongoListDatabases(arg1) {
  return window['go']['main']['App']['MongoListDatabases'](arg1);
}

export function MongoListIndexes(arg1, arg2, arg3) {
  return window['go']['main']['App']['MongoListIndexes'](arg1, arg2, arg3);
}

export function MongoPing(arg1) {
  return window['go']['main']['App']['MongoPing'](arg1);
}

export function MongoUpdateOne(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['MongoUpdateOne'](arg1, arg2, arg3, arg4, arg5);
}

export function OnConnectionsChanged(arg1) {
  return window['go']['main']['App']['OnConnectionsChanged'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFileDialogFiltered(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileDialogFiltered'](arg1, arg2, arg3);
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function OpenPathInExplorer(arg1) {
  return window['go']['main']['App']['OpenPathInExplorer'](arg1);
}

export function RDPHide(arg1) {
  return window['go']['main']['App']['RDPHide'](arg1);
}

export function RDPSetFocus(arg1, arg2) {
  return window['go']['main']['App']['RDPSetFocus'](arg1, arg2);
}

export function RDPSetPosition(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RDPSetPosition'](arg1, arg2, arg3, arg4, arg5);
}

export function RDPShow(arg1) {
  return window['go']['main']['App']['RDPShow'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReadFileChunkBase64(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReadFileChunkBase64'](arg1, arg2, arg3);
}

export function RecordRecentConnection(arg1) {
  return window['go']['main']['App']['RecordRecentConnection'](arg1);
}

export function RedisDBSize(arg1) {
  return window['go']['main']['App']['RedisDBSize'](arg1);
}

export function RedisDeleteKey(arg1, arg2) {
  return window['go']['main']['App']['RedisDeleteKey'](arg1, arg2);
}

export function RedisGetHashAll(arg1, arg2) {
  return window['go']['main']['App']['RedisGetHashAll'](arg1, arg2);
}

export function RedisGetKeyInfo(arg1, arg2) {
  return window['go']['main']['App']['RedisGetKeyInfo'](arg1, arg2);
}

export function RedisGetKeyTTL(arg1, arg2) {
  return window['go']['main']['App']['RedisGetKeyTTL'](arg1, arg2);
}

export function RedisGetListRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedisGetListRange'](arg1, arg2, arg3, arg4);
}

export function RedisGetSetAll(arg1, arg2) {
  return window['go']['main']['App']['RedisGetSetAll'](arg1, arg2);
}

export function RedisGetSortedSetRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedisGetSortedSetRange'](arg1, arg2, arg3, arg4);
}

export function RedisGetString(arg1, arg2) {
  return window['go']['main']['App']['RedisGetString'](arg1, arg2);
}

export function RedisHashDel(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedisHashDel'](arg1, arg2, arg3);
}

export function RedisHashSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedisHashSet'](arg1, arg2, arg3, arg4);
}

export function RedisKeyExists(arg1, arg2) {
  return window['go']['main']['App']['RedisKeyExists'](arg1, arg2);
}

export function RedisKeyspaceInfo(arg1) {
  return window['go']['main']['App']['RedisKeyspaceInfo'](arg1);
}

export function RedisListPop(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedisListPop'](arg1, arg2, arg3);
}

export function RedisListPush(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedisListPush'](arg1, arg2, arg3, arg4);
}

export function RedisListRemove(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedisListRemove'](arg1, arg2, arg3, arg4);
}

export function RedisListSet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedisListSet'](arg1, arg2, arg3, arg4);
}

export function RedisPing(arg1) {
  return window['go']['main']['App']['RedisPing'](arg1);
}

export function RedisScanKeys(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RedisScanKeys'](arg1, arg2, arg3, arg4);
}

export function RedisSetAdd(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedisSetAdd'](arg1, arg2, arg3);
}

export function RedisSetKeyTTL(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedisSetKeyTTL'](arg1, arg2, arg3);
}

export function RedisSetRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedisSetRemove'](arg1, arg2, arg3);
}

export function RedisSetString(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedisSetString'](arg1, arg2, arg3);
}

export function RedisSwitchDB(arg1, arg2) {
  return window['go']['main']['App']['RedisSwitchDB'](arg1, arg2);
}

export function RedisZSetAdd(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedisZSetAdd'](arg1, arg2, arg3);
}

export function RedisZSetRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['RedisZSetRemove'](arg1, arg2, arg3);
}

export function RegisterSessionForPanel(arg1, arg2) {
  return window['go']['main']['App']['RegisterSessionForPanel'](arg1, arg2);
}

export function RemoveTempFile(arg1) {
  return window['go']['main']['App']['RemoveTempFile'](arg1);
}

export function SaveAIConfig(arg1) {
  return window['go']['main']['App']['SaveAIConfig'](arg1);
}

export function SaveAISessions(arg1) {
  return window['go']['main']['App']['SaveAISessions'](arg1);
}

export function SaveConnections(arg1) {
  return window['go']['main']['App']['SaveConnections'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveFileDialogFiltered(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFileDialogFiltered'](arg1, arg2, arg3, arg4);
}

export function SaveLocalState(arg1) {
  return window['go']['main']['App']['SaveLocalState'](arg1);
}

export function SaveQuickCommands(arg1) {
  return window['go']['main']['App']['SaveQuickCommands'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveTerminalHistory(arg1) {
  return window['go']['main']['App']['SaveTerminalHistory'](arg1);
}

export function SaveTunnels(arg1) {
  return window['go']['main']['App']['SaveTunnels'](arg1);
}

export function SaveWindowState(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveWindowState'](arg1, arg2, arg3, arg4, arg5);
}

export function SessionEndZmodem(arg1) {
  return window['go']['main']['App']['SessionEndZmodem'](arg1);
}

export function SessionResize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SessionResize'](arg1, arg2, arg3);
}

export function SessionStartZmodem(arg1) {
  return window['go']['main']['App']['SessionStartZmodem'](arg1);
}

export function SessionWrite(arg1, arg2) {
  return window['go']['main']['App']['SessionWrite'](arg1, arg2);
}

export function SessionWriteBinary(arg1, arg2) {
  return window['go']['main']['App']['SessionWriteBinary'](arg1, arg2);
}

export function SetBackgroundImage(arg1) {
  return window['go']['main']['App']['SetBackgroundImage'](arg1);
}

export function SetDefaultSessionLogDir(arg1) {
  return window['go']['main']['App']['SetDefaultSessionLogDir'](arg1);
}

export function SetMonitorActiveTab(arg1, arg2) {
  return window['go']['main']['App']['SetMonitorActiveTab'](arg1, arg2);
}

export function SetMonitorPaused(arg1, arg2) {
  return window['go']['main']['App']['SetMonitorPaused'](arg1, arg2);
}

export function SftpCancelTransfer(arg1, arg2) {
  return window['go']['main']['App']['SftpCancelTransfer'](arg1, arg2);
}

export function SftpChangeLocalDir(arg1, arg2) {
  return window['go']['main']['App']['SftpChangeLocalDir'](arg1, arg2);
}

export function SftpChangeRemoteDir(arg1, arg2) {
  return window['go']['main']['App']['SftpChangeRemoteDir'](arg1, arg2);
}

export function SftpChmod(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpChmod'](arg1, arg2, arg3);
}

export function SftpCopy(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpCopy'](arg1, arg2, arg3);
}

export function SftpGet(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpGet'](arg1, arg2, arg3, arg4);
}

export function SftpGetContent(arg1, arg2) {
  return window['go']['main']['App']['SftpGetContent'](arg1, arg2);
}

export function SftpListLocal(arg1, arg2) {
  return window['go']['main']['App']['SftpListLocal'](arg1, arg2);
}

export function SftpListLocalDrives(arg1) {
  return window['go']['main']['App']['SftpListLocalDrives'](arg1);
}

export function SftpListRemote(arg1, arg2) {
  return window['go']['main']['App']['SftpListRemote'](arg1, arg2);
}

export function SftpLocalCopy(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpLocalCopy'](arg1, arg2, arg3);
}

export function SftpLocalGetContent(arg1, arg2) {
  return window['go']['main']['App']['SftpLocalGetContent'](arg1, arg2);
}

export function SftpLocalMkdir(arg1, arg2) {
  return window['go']['main']['App']['SftpLocalMkdir'](arg1, arg2);
}

export function SftpLocalMove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpLocalMove'](arg1, arg2, arg3);
}

export function SftpLocalPutContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpLocalPutContent'](arg1, arg2, arg3, arg4);
}

export function SftpLocalRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpLocalRemove'](arg1, arg2, arg3);
}

export function SftpLocalRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpLocalRename'](arg1, arg2, arg3);
}

export function SftpMakeDir(arg1, arg2) {
  return window['go']['main']['App']['SftpMakeDir'](arg1, arg2);
}

export function SftpMove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpMove'](arg1, arg2, arg3);
}

export function SftpPauseTransfer(arg1, arg2) {
  return window['go']['main']['App']['SftpPauseTransfer'](arg1, arg2);
}

export function SftpPut(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpPut'](arg1, arg2, arg3, arg4);
}

export function SftpPutContent(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SftpPutContent'](arg1, arg2, arg3, arg4);
}

export function SftpRemove(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRemove'](arg1, arg2, arg3);
}

export function SftpRename(arg1, arg2, arg3) {
  return window['go']['main']['App']['SftpRename'](arg1, arg2, arg3);
}

export function SftpResumeTransfer(arg1, arg2) {
  return window['go']['main']['App']['SftpResumeTransfer'](arg1, arg2);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel(arg1) {
  return window['go']['main']['App']['StopTunnel'](arg1);
}

export function SyncChangePassword(arg1, arg2) {
  return window['go']['main']['App']['SyncChangePassword'](arg1, arg2);
}

export function SyncConfigureRepo(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncConfigureRepo'](arg1, arg2, arg3, arg4);
}

export function SyncDeleteRepo() {
  return window['go']['main']['App']['SyncDeleteRepo']();
}

export function SyncGetConfig() {
  return window['go']['main']['App']['SyncGetConfig']();
}

export function SyncNow() {
  return window['go']['main']['App']['SyncNow']();
}

export function SyncResolveConflict(arg1) {
  return window['go']['main']['App']['SyncResolveConflict'](arg1);
}

export function SyncSaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SyncSaveConfig'](arg1, arg2);
}

export function SyncTestConnection() {
  return window['go']['main']['App']['SyncTestConnection']();
}

export function SyncVerifyPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SyncVerifyPassword'](arg1, arg2, arg3);
}

export function TruncateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['TruncateTable'](arg1, arg2, arg3);
}

export function UnregisterSession(arg1) {
  return window['go']['main']['App']['UnregisterSession'](arg1);
}

export function WriteFileBase64(arg1, arg2) {
  return window['go']['main']['App']['WriteFileBase64'](arg1, arg2);
}

export function WriteTempFile(arg1, arg2) {
  return window['go']['main']['App']['WriteTempFile'](arg1, arg2);
}
